# Kong Load Balancing Configuration for High Throughput
# Target: ≥5000 requests/second
# Requirements: 7.4

# Kong Gateway Configuration for High Throughput Load Balancing
version: '3.8'

services:
  kong:
    image: kong:3.4-alpine
    container_name: eagle-kong-gateway
    restart: unless-stopped
    
    environment:
      # Database configuration
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      
      # Performance optimization for high throughput
      KONG_WORKER_PROCESSES: auto
      KONG_WORKER_CONNECTIONS: 4096
      KONG_WORKER_RLIMIT_NOFILE: 65536
      
      # Nginx optimization for throughput
      KONG_NGINX_HTTP_KEEPALIVE_TIMEOUT: 75s
      KONG_NGINX_HTTP_KEEPALIVE_REQUESTS: 1000
      KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE: 128k
      KONG_NGINX_HTTP_CLIENT_HEADER_BUFFER_SIZE: 8k
      KONG_NGINX_HTTP_LARGE_CLIENT_HEADER_BUFFERS: "8 64k"
      KONG_NGINX_HTTP_CLIENT_MAX_BODY_SIZE: 10m
      
      # Upstream configuration for high throughput
      KONG_UPSTREAM_KEEPALIVE_POOL_SIZE: 60
      KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS: 1000
      KONG_UPSTREAM_KEEPALIVE_IDLE_TIMEOUT: 60s
      
      # Proxy configuration
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      
      # Performance tuning
      KONG_LOG_LEVEL: warn
      KONG_NGINX_DAEMON: "off"
      KONG_NGINX_WORKER_PROCESSES: auto
      
      # Memory optimization
      KONG_MEM_CACHE_SIZE: 128m
      KONG_NGINX_HTTP_LUA_SHARED_DICT: "prometheus_metrics 5m"
      
      # SSL/TLS optimization (if using HTTPS)
      KONG_SSL_CIPHER_SUITE: intermediate
      KONG_SSL_CIPHERS: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
      KONG_SSL_PROTOCOLS: TLSv1.2 TLSv1.3
      
    ports:
      - "8000:8000"  # Proxy port
      - "8001:8001"  # Admin API port
      - "8443:8443"  # Proxy SSL port
      - "8444:8444"  # Admin API SSL port
      
    volumes:
      - ./kong-config:/opt/kong/config
      - ./kong-logs:/opt/kong/logs
      
    networks:
      - eagle-network
      
    depends_on:
      - postgres
      
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:15-alpine
    container_name: eagle-kong-db
    restart: unless-stopped
    
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong_password
      
      # PostgreSQL performance optimization
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_CHECKPOINT_COMPLETION_TARGET: 0.9
      POSTGRES_WAL_BUFFERS: 16MB
      POSTGRES_DEFAULT_STATISTICS_TARGET: 100
      POSTGRES_RANDOM_PAGE_COST: 1.1
      POSTGRES_EFFECTIVE_IO_CONCURRENCY: 200
      
    volumes:
      - kong-postgres-data:/var/lib/postgresql/data
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
      
    networks:
      - eagle-network
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Kong Database Migration
  kong-migration:
    image: kong:3.4-alpine
    container_name: eagle-kong-migration
    
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      
    command: kong migrations bootstrap
    
    networks:
      - eagle-network
      
    depends_on:
      - postgres
      
    restart: "no"

  # Prometheus for monitoring Kong metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: eagle-prometheus
    restart: unless-stopped
    
    ports:
      - "9090:9090"
      
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      
    networks:
      - eagle-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: eagle-grafana
    restart: unless-stopped
    
    ports:
      - "3000:3000"
      
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: false
      
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      
    networks:
      - eagle-network

volumes:
  kong-postgres-data:
  prometheus-data:
  grafana-data:

networks:
  eagle-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

---
# Kong Configuration for Eagle Microservices Load Balancing

# Service definitions for each microservice
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: eagle-throughput-optimization
proxy:
  # Connection settings optimized for throughput
  connect_timeout: 5000
  read_timeout: 60000
  write_timeout: 60000
  
  # Retries configuration
  retries: 3
  
upstream:
  # Load balancing algorithm
  algorithm: round-robin
  
  # Health checks for high availability
  healthchecks:
    active:
      type: http
      http_path: /actuator/health
      healthy:
        interval: 10
        successes: 3
      unhealthy:
        interval: 10
        http_failures: 3
        timeouts: 3
    passive:
      healthy:
        successes: 3
      unhealthy:
        http_failures: 3
        timeouts: 3
  
  # Connection pooling for throughput
  slots: 1000
  
---
# MS-Alert Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: ms-alert-service
  annotations:
    konghq.com/override: eagle-throughput-optimization
spec:
  selector:
    app: ms-alert
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
# MS-Customer Service Configuration  
apiVersion: v1
kind: Service
metadata:
  name: ms-customer-service
  annotations:
    konghq.com/override: eagle-throughput-optimization
spec:
  selector:
    app: ms-customer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP

---
# MS-Orchestrator Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: ms-orchestrator-service
  annotations:
    konghq.com/override: eagle-throughput-optimization
spec:
  selector:
    app: ms-orchestrator
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP

---
# MS-Transaction Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: ms-transaction-service
  annotations:
    konghq.com/override: eagle-throughput-optimization
spec:
  selector:
    app: ms-transaction
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP

---
# MS-API Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: ms-api-service
  annotations:
    konghq.com/override: eagle-throughput-optimization
spec:
  selector:
    app: ms-api
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP

---
# MS-Enrichment Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: ms-enrichment-service
  annotations:
    konghq.com/override: eagle-throughput-optimization
spec:
  selector:
    app: ms-enrichment
  ports:
    - name: http
      port: 8085
      targetPort: 8085
  type: ClusterIP

---
# Kong Ingress Routes for Load Balancing
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eagle-api-gateway
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: eagle-throughput-optimization
    # Rate limiting for throughput control
    konghq.com/plugins: eagle-rate-limiting, eagle-prometheus
    # Load balancing configuration
    konghq.com/load-balance: round_robin
spec:
  rules:
    - host: api.eagle.local
      http:
        paths:
          # Alert service routes
          - path: /api/v1/alerts
            pathType: Prefix
            backend:
              service:
                name: ms-alert-service
                port:
                  number: 8080
          
          # Customer service routes  
          - path: /api/v1/customers
            pathType: Prefix
            backend:
              service:
                name: ms-customer-service
                port:
                  number: 8081
          
          # Orchestrator service routes
          - path: /api/v1/orchestrator
            pathType: Prefix
            backend:
              service:
                name: ms-orchestrator-service
                port:
                  number: 8082
          
          # Transaction service routes
          - path: /api/v1/transactions
            pathType: Prefix
            backend:
              service:
                name: ms-transaction-service
                port:
                  number: 8083
          
          # API service routes
          - path: /api/v1/api
            pathType: Prefix
            backend:
              service:
                name: ms-api-service
                port:
                  number: 8084
          
          # Enrichment service routes
          - path: /api/v1/enrichment
            pathType: Prefix
            backend:
              service:
                name: ms-enrichment-service
                port:
                  number: 8085

---
# Rate Limiting Plugin for Throughput Control
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: eagle-rate-limiting
config:
  # Allow high throughput while preventing abuse
  minute: 300000    # 5000 req/s * 60s = 300,000 per minute
  hour: 18000000    # 5000 req/s * 3600s = 18,000,000 per hour
  policy: local
  hide_client_headers: false
  fault_tolerant: true
plugin: rate-limiting

---
# Prometheus Plugin for Metrics Collection
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: eagle-prometheus
config:
  per_consumer: true
  status_code_metrics: true
  latency_metrics: true
  bandwidth_metrics: true
  upstream_health_metrics: true
plugin: prometheus

---
# Request Size Limiting Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: eagle-request-size-limiting
config:
  allowed_payload_size: 10  # 10MB max request size
plugin: request-size-limiting

---
# Response Rate Limiting Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: eagle-response-ratelimiting
config:
  limits:
    video: 
      minute: 10
    image:
      minute: 20
plugin: response-ratelimiting

---
# CORS Plugin for Cross-Origin Requests
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: eagle-cors
config:
  origins:
    - "http://localhost:3000"
    - "https://eagle.fusionx.pro"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - Authorization
  exposed_headers:
    - X-Auth-Token
  credentials: true
  max_age: 3600
plugin: cors