apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
    istio-operator-managed: Reconcile
    istio-injection: disabled
  annotations:
    istio.io/rev: default